import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { fetchAbilityData, fetchChampionNames, getAbilities } from 'lib/abilities'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const data = await getAbilities()
  console.log(data);
  return {
    props: {
      // abilities: JSON.stringify(data)
      abilities: JSON.stringify(data)
    }
  }
};

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          { props.abilities }
        </div>
      </main>
    </>
  )
}
